ARG version
FROM almalinux:${version:-9}
ARG course="docker" \
    duration="150hrs" \
    author="siva"
RUN echo "course is ${course}, duration is ${duration}, author is ${author}"
CMD [ "sleep", "100" ]
